// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBz6iuTrz2BVE6owjH_dvugruemAIw2ENY',
    appId: '1:299123234077:web:63073a212178b58b343df4',
    messagingSenderId: '299123234077',
    projectId: 'parkeerapp-d01e8',
    authDomain: 'parkeerapp-d01e8.firebaseapp.com',
    storageBucket: 'parkeerapp-d01e8.appspot.com',
    measurementId: 'G-766XYTFZ6C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeNJMpaSPM5xIvzqrcHYjQOGo8lL4AK54',
    appId: '1:299123234077:android:da953121bfcfcafc343df4',
    messagingSenderId: '299123234077',
    projectId: 'parkeerapp-d01e8',
    storageBucket: 'parkeerapp-d01e8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzh7qPCZXbb0wNRoAul1ZLdirsb8wyP3I',
    appId: '1:299123234077:ios:1668a8e96057dae7343df4',
    messagingSenderId: '299123234077',
    projectId: 'parkeerapp-d01e8',
    storageBucket: 'parkeerapp-d01e8.appspot.com',
    iosClientId: '299123234077-25t89fsc0b0bkvpf3i0fp91ha21bm0cj.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzh7qPCZXbb0wNRoAul1ZLdirsb8wyP3I',
    appId: '1:299123234077:ios:1668a8e96057dae7343df4',
    messagingSenderId: '299123234077',
    projectId: 'parkeerapp-d01e8',
    storageBucket: 'parkeerapp-d01e8.appspot.com',
    iosClientId: '299123234077-25t89fsc0b0bkvpf3i0fp91ha21bm0cj.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );
}
